<?
require_once("initsession.php");
require_once("../includes/inc_config_variable.php");
require_once("../classes/database.php");
require_once("../classes/generate_form.php");
require_once("../classes/form.php");
require_once("../classes/upload.php");
require_once("../classes/menu.php");
require_once("../classes/user.php");
require_once("../classes/openid.php");
require_once("../classes/html_cleanup.php");
require_once("../functions/resize_image.php");
require_once("../functions/functions.php");
require_once("../functions/date_functions.php");
require_once("../functions/reading_funtion.php");
require_once("../functions/listening_function.php");
require_once("../functions/writing_function.php");
require_once("../functions/rewrite_functions.php");
require_once("../includes/inc_config_website.php");
$myuser = new user();
?>